spring:
    application:
        name: NerdySoft_Tech_Task

    datasource:
        url: jdbc:postgresql://localhost:5432/nerdySoft_tech_task
        username: postgres
        password: 123456789

    jpa:
        hibernate:
            ddl-auto: update

server:
    servlet:
        context-path: /api/v1

springdoc:
    swagger-ui:
        path: /api-docs/ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /api-docs
    default-produces-media-type: application/json
    default-consumes-media-type: application/json

custom:
    validation:
        bookBorrowLimit: 10

