spring:
    application:
        name: NerdySoft_Tech_Task

    datasource:
        url: jdbc:postgresql://localhost:5432/nerdySoft_tech_task
        username: postgres
        password: 123456789

    jpa:
        hibernate:
            ddl-auto: update

server:
    servlet:
        context-path: /api/v1

custom:
    validation:
        bookBorrowLimit: 5

